// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr2tyYYcGf3nDdWKxqUFB3L7bJBRZfnwk',
    appId: '1:582115471020:web:157627085f71c4b19d7909',
    messagingSenderId: '582115471020',
    projectId: 'yts-mobile-5c23e',
    authDomain: 'yts-mobile-5c23e.firebaseapp.com',
    storageBucket: 'yts-mobile-5c23e.appspot.com',
    measurementId: 'G-TEL3Y2PF14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNNuZL85H0EebWbVH3ihcRGkHBBaeDHZU',
    appId: '1:582115471020:android:a45ec6e8a12dcce39d7909',
    messagingSenderId: '582115471020',
    projectId: 'yts-mobile-5c23e',
    storageBucket: 'yts-mobile-5c23e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZIpSTdP5Nl3p04E3L1vcxOGqctWeTj6E',
    appId: '1:582115471020:ios:d304a1cea82575499d7909',
    messagingSenderId: '582115471020',
    projectId: 'yts-mobile-5c23e',
    storageBucket: 'yts-mobile-5c23e.appspot.com',
    iosClientId:
        '582115471020-t9ph3lrv8q3pjejbufq2ggehrelb8u7k.apps.googleusercontent.com',
    iosBundleId: 'com.yts.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZIpSTdP5Nl3p04E3L1vcxOGqctWeTj6E',
    appId: '1:582115471020:ios:825bfa2ce67d99e39d7909',
    messagingSenderId: '582115471020',
    projectId: 'yts-mobile-5c23e',
    storageBucket: 'yts-mobile-5c23e.appspot.com',
    iosClientId:
        '582115471020-55no34roucc3g723bpt58dascc1gh27j.apps.googleusercontent.com',
    iosBundleId: 'com.yts.mobile.ytsMobile',
  );
}
